// GENERATED BY CLAUDE - 2025-11-03

// ===== User & Authentication =====
export interface User {
  id: number;
  nome: string;
  nome_funcionario?: string;
  email: string;
  funcao: 'Admin' | 'Diretor' | 'Professor' | 'Secretario';
  token?: string;
}

export interface LoginCredentials {
  email: string;
  password: string;
}

export interface AuthResponse {
  token: string;
  user: User;
}

// ===== Aluno (Student) =====
export interface Aluno {
  id_alunos: number;
  nome_aluno: string;
  data_nascimento: string;
  genero: 'M' | 'F';
  bi_certidao?: string;
  nome_mae?: string;
  nome_pai?: string;
  contacto_aluno?: string;
  morada?: string;
  turma?: string;
  classe?: string;
  ano_letivo?: number;
  estado: 'Ativo' | 'Inativo' | 'Suspenso';
  foto_url?: string;
  encarregado?: Encarregado;
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateAlunoDto {
  nome_aluno: string;
  data_nascimento: string;
  genero: 'M' | 'F';
  bi_certidao?: string;
  nome_mae?: string;
  nome_pai?: string;
  contacto_aluno?: string;
  morada?: string;
  turma?: string;
  classe?: string;
  ano_letivo?: number;
  id_encarregado?: number;
}

// ===== Encarregado (Guardian) =====
export interface Encarregado {
  id_encarregados: number;
  nome_encarregado: string;
  parentesco: string;
  contacto1: string;
  contacto2?: string;
  contacto3?: string;
  morada?: string;
  email?: string;
  profissao?: string;
  local_trabalho?: string;
  bi?: string;
  estado: 'Ativo' | 'Inativo';
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateEncarregadoDto {
  nome_encarregado: string;
  parentesco: string;
  contacto1: string;
  contacto2?: string;
  contacto3?: string;
  morada?: string;
  email?: string;
  profissao?: string;
  local_trabalho?: string;
  bi?: string;
}

// ===== Turma (Class) =====
export interface Turma {
  id_turmas: number;
  nome_turma: string;
  classe: string;
  ano_letivo: number;
  turno: 'Manhã' | 'Tarde' | 'Noite';
  capacidade_maxima?: number;
  sala?: string;
  estado: 'Ativa' | 'Inativa';
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateTurmaDto {
  nome_turma: string;
  classe: string;
  ano_letivo: number;
  turno: 'Manhã' | 'Tarde' | 'Noite';
  capacidade_maxima?: number;
  sala?: string;
}

// ===== Classe (Grade/Level) =====
export interface Classe {
  id_classes: number;
  nome_classe: string;
  turma: string;
  ano_letivo: number;
  disciplina: string;
  carga_horaria: number;
  professor: Professor;
  createdAt?: string;
  updatedAt?: string;
}

// ===== Professor =====
export interface Professor {
  id_professores?: number;
  nome: string;
  contacto1: string;
  contacto2?: string;
  contacto3?: string;
  email?: string;
  especialidade?: string;
  estado?: 'Ativo' | 'Inativo';
}

// ===== Funcionario (Staff) =====
export interface Funcionario {
  id_funcionarios: number;
  nome_funcionario: string;
  funcao: string;
  contacto1: string;
  contacto2?: string;
  email?: string;
  salario?: number;
  data_admissao?: string;
  estado: 'Ativo' | 'Inativo';
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateFuncionarioDto {
  nome_funcionario: string;
  funcao: string;
  contacto1: string;
  contacto2?: string;
  email?: string;
  password?: string;
  salario?: number;
  data_admissao?: string;
}

// ===== Pagamento (Payment) =====
export interface Pagamento {
  id_pagamentos: number;
  id_alunos: number;
  aluno?: Aluno;
  tipo_pagamento: 'Mensalidade' | 'Inscrição' | 'Material' | 'Outro';
  valor: number;
  data_pagamento: string;
  mes_referencia?: string;
  estado: 'Pago' | 'Pendente' | 'Atrasado' | 'Cancelado';
  metodo_pagamento?: 'Dinheiro' | 'TPA' | 'Transferência' | 'M-Pesa';
  comprovativo?: string;
  observacoes?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface CreatePagamentoDto {
  id_alunos: number;
  tipo_pagamento: 'Mensalidade' | 'Inscrição' | 'Material' | 'Outro';
  valor: number;
  data_pagamento: string;
  mes_referencia?: string;
  metodo_pagamento?: 'Dinheiro' | 'TPA' | 'Transferência' | 'M-Pesa';
  observacoes?: string;
}

// ===== Presença (Attendance) =====
export interface Presenca {
  id_presencas: number;
  id_alunos: number;
  aluno?: Aluno;
  id_classes?: number;
  data_presenca: string;
  estado: 'Presente' | 'Falta' | 'Justificada';
  observacoes?: string;
  turma?: string;
  classe?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface CreatePresencaDto {
  id_alunos: number;
  id_classes?: number;
  data_presenca: string;
  estado: 'Presente' | 'Falta' | 'Justificada';
  observacoes?: string;
}

// ===== Nota (Grade/Score) =====
export interface Nota {
  id_notas: number;
  id_alunos: number;
  aluno?: Aluno;
  disciplina: string;
  trimestre: 1 | 2 | 3;
  ano_letivo: number;
  nota_mac1?: number;
  nota_mac2?: number;
  nota_mac3?: number;
  media_mac?: number;
  nota_exame?: number;
  media_final?: number;
  observacoes?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateNotaDto {
  id_alunos: number;
  disciplina: string;
  trimestre: 1 | 2 | 3;
  ano_letivo: number;
  nota_mac1?: number;
  nota_mac2?: number;
  nota_mac3?: number;
  nota_exame?: number;
  observacoes?: string;
}

// ===== Exame/Pacote (Exam Package) =====
export interface ExamePacote {
  id: number;
  nome: string;
  descricao?: string;
  classe: string;
  ano_letivo: number;
  data_inicio?: string;
  data_fim?: string;
  disciplinas: string[];
  estado: 'Planejado' | 'Em andamento' | 'Concluído';
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateExamePacoteDto {
  nome: string;
  descricao?: string;
  classe: string;
  ano_letivo: number;
  data_inicio?: string;
  data_fim?: string;
  disciplinas: string[];
}

// ===== Disciplina (Subject) =====
export interface Disciplina {
  id_disciplinas: number;
  nome_disciplina: string;
  codigo?: string;
  descricao?: string;
  carga_horaria?: number;
  estado: 'Ativa' | 'Inativa';
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateDisciplinaDto {
  nome_disciplina: string;
  codigo?: string;
  descricao?: string;
  carga_horaria?: number;
}

// ===== Horário (Schedule) =====
export interface Horario {
  id: number;
  turma: string;
  classe: string;
  dia_semana: 'Segunda' | 'Terça' | 'Quarta' | 'Quinta' | 'Sexta' | 'Sábado';
  hora_inicio: string;
  hora_fim: string;
  disciplina: string;
  professor?: Professor;
  sala?: string;
  ano_letivo: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface CreateHorarioDto {
  turma: string;
  classe: string;
  dia_semana: 'Segunda' | 'Terça' | 'Quarta' | 'Quinta' | 'Sexta' | 'Sábado';
  hora_inicio: string;
  hora_fim: string;
  disciplina: string;
  id_professor?: number;
  sala?: string;
  ano_letivo: number;
}

// ===== Relatório (Report) =====
export interface Relatorio {
  id: number;
  tipo: 'Financeiro' | 'Acadêmico' | 'Presença' | 'Geral';
  titulo: string;
  descricao?: string;
  periodo_inicio: string;
  periodo_fim: string;
  gerado_por: string;
  gerado_em: string;
  arquivo_url?: string;
  formato: 'PDF' | 'Excel' | 'CSV';
}

export interface CreateRelatorioDto {
  tipo: 'Financeiro' | 'Acadêmico' | 'Presença' | 'Geral';
  titulo: string;
  descricao?: string;
  periodo_inicio: string;
  periodo_fim: string;
  formato: 'PDF' | 'Excel' | 'CSV';
  filtros?: Record<string, any>;
}

// ===== Notificação =====
export interface Notificacao {
  id: number;
  titulo: string;
  mensagem: string;
  tipo: 'info' | 'success' | 'warning' | 'error';
  destinatario?: string;
  lida: boolean;
  createdAt: string;
}

// ===== Dashboard Stats =====
export interface DashboardStats {
  totalAlunos: number;
  totalEncarregados: number;
  totalFuncionarios: number;
  totalPagamentosHoje: number;
  totalPagamentosMes: number;
  pagamentosPendentes: number;
  presencasHoje: number;
  faltasHoje: number;
  proximosEventos: Array<{
    id: number;
    titulo: string;
    data: string;
    tipo: string;
  }>;
}

// ===== Common Types =====
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: {
    message: string;
    code?: string;
  };
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  totalPages: number;
}

export interface FilterParams {
  search?: string;
  page?: number;
  pageSize?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
  [key: string]: any;
}
