// GENERATED BY CLAUDE - 2025-11-03
import api from './api';
import { ExamePacote, CreateExamePacoteDto } from '../types/models';

export const examesService = {
  getAll: async (): Promise<ExamePacote[]> => {
    // TODO: Integrar com endpoint real
    const response = await api.get('/exames');
    return response.data;
  },

  getById: async (id: number): Promise<ExamePacote> => {
    const response = await api.get(`/exames/${id}`);
    return response.data;
  },

  create: async (data: CreateExamePacoteDto): Promise<ExamePacote> => {
    const response = await api.post('/exames', data);
    return response.data;
  },

  update: async (id: number, data: Partial<CreateExamePacoteDto>): Promise<ExamePacote> => {
    const response = await api.put(`/exames/${id}`, data);
    return response.data;
  },

  delete: async (id: number): Promise<void> => {
    await api.delete(`/exames/${id}`);
  },

  getByClasse: async (classe: string): Promise<ExamePacote[]> => {
    const response = await api.get(`/exames/classe/${classe}`);
    return response.data;
  }
};

export default examesService;
