// GENERATED BY CLAUDE - 2025-11-03
import api from './api';
import { DashboardStats } from '../types/models';

export const dashboardService = {
  getStats: async (): Promise<DashboardStats> => {
    // TODO: Integrar com endpoint real
    const response = await api.get('/dashboard/stats');
    return response.data;
  },

  getRecentActivity: async (): Promise<any[]> => {
    const response = await api.get('/dashboard/recent-activity');
    return response.data;
  },

  getFinancialSummary: async (month?: number, year?: number): Promise<any> => {
    const params = new URLSearchParams();
    if (month) params.append('month', month.toString());
    if (year) params.append('year', year.toString());
    
    const response = await api.get(`/dashboard/financial?${params.toString()}`);
    return response.data;
  }
};

export default dashboardService;
