// GENERATED BY CLAUDE - 2025-11-03
import { useState, useEffect } from 'react';
import { Calendar, Plus } from 'lucide-react';

export default function HorariosPage() {
  const [horarios, setHorarios] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchHorarios();
  }, []);

  const fetchHorarios = async () => {
    try {
      // TODO: Integrar com API real
      const res = await fetch('http://localhost:3000/api/horarios');
      if (res.ok) {
        const data = await res.json();
        setHorarios(data);
      }
    } catch (error) {
      console.error('Erro ao carregar horários:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="card">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-text-primary">Horários</h2>
            <p className="text-sm text-neutral-gray mt-1">Gestão de horários escolares</p>
          </div>
          <button className="btn-primary flex items-center gap-2">
            <Plus size={16} /> Novo Horário
          </button>
        </div>
      </div>

      <div className="card">
        {loading ? (
          <p className="text-neutral-gray">Carregando...</p>
        ) : horarios.length === 0 ? (
          <div className="text-center py-12">
            <Calendar className="mx-auto text-neutral-gray mb-4" size={48} />
            <p className="text-neutral-gray">Nenhum horário cadastrado</p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="min-w-full">
              <thead className="table-header">
                <tr>
                  <th className="px-4 py-3 text-left">Dia</th>
                  <th className="px-4 py-3 text-left">Horário</th>
                  <th className="px-4 py-3 text-left">Turma</th>
                  <th className="px-4 py-3 text-left">Disciplina</th>
                  <th className="px-4 py-3 text-left">Professor</th>
                </tr>
              </thead>
              <tbody>
                {horarios.map((h, i) => (
                  <tr key={i} className="table-row">
                    <td className="px-4 py-3">{h.dia_semana}</td>
                    <td className="px-4 py-3">{h.hora_inicio} - {h.hora_fim}</td>
                    <td className="px-4 py-3">{h.turma}</td>
                    <td className="px-4 py-3">{h.disciplina}</td>
                    <td className="px-4 py-3">{h.professor}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
