// GENERATED BY CLAUDE - 2025-11-03
import { useState } from 'react';
import Dialog from '../../components/Dialog';

interface LoginProps {
  onLoginSuccess: (email: string, password: string) => void;
  onForgotPassword: () => void;
}

export default function LoginPage({ onLoginSuccess, onForgotPassword }: LoginProps) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [dialog, setDialog] = useState<{
    isOpen: boolean;
    title: string;
    message: string;
    type: 'error' | 'success' | 'info' | 'warning';
  }>({ isOpen: false, title: '', message: '', type: 'info' });

  // Validação: Email e senha
  const validarEmail = (val: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val);
  const validarPassword = (val: string) => val.trim().length >= 6;

  const showDialog = (title: string, message: string, type: 'error' | 'success' | 'info' | 'warning' = 'info') => {
    setDialog({ isOpen: true, title, message, type });
  };

  const closeDialog = () => {
    setDialog({ ...dialog, isOpen: false });
  };

  const handleLogin = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    
    if (!validarEmail(email)) {
      showDialog('Email Inválido', 'Por favor, insira um endereço de email válido.', 'warning');
      return;
    }
    
    if (!validarPassword(password)) {
      showDialog('Senha Inválida', 'A senha deve ter no mínimo 6 caracteres.', 'warning');
      return;
    }
    
    setIsLoading(true);
    try {
      await onLoginSuccess(email, password);
    } catch (error) {
      // Erro já tratado no App.tsx
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <>
      <Dialog
        isOpen={dialog.isOpen}
        onClose={closeDialog}
        title={dialog.title}
        message={dialog.message}
        type={dialog.type}
      />
      <div className="fixed inset-0 bg-accent flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-lg w-full max-w-md p-8 border border-border-light">
        {/* Título */}
        <div className="text-center mb-8">
          <div className="w-20 h-20 rounded-full bg-primary flex items-center justify-center mx-auto mb-4">
            <img
              src="https://cdn-icons-png.flaticon.com/512/29/29302.png"
              alt="Livro"
              className="w-12 h-12 brightness-0 invert"
            />
          </div>
          <h2 className="text-2xl font-semibold text-text-primary">
            Sistema de Gestão Escolar
          </h2>
          <p className="text-sm text-neutral-gray mt-2">Faça login para continuar</p>
        </div>

        {/* Campos */}
        <form onSubmit={handleLogin} className="space-y-4">
          <div>
            <label className="block mb-2 text-sm font-medium text-text-primary">Email</label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="seu.email@escola.com"
              className="input-field"
              aria-label="Email"
              disabled={isLoading}
            />
          </div>
          <div>
            <label className="block mb-2 text-sm font-medium text-text-primary">Senha</label>
            <input
              type="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              placeholder="Digite sua senha"
              className="input-field"
              aria-label="Senha"
              disabled={isLoading}
              onKeyPress={(e) => e.key === 'Enter' && handleLogin()}
            />
          </div>

          {/* Botões */}
          <div className="flex gap-3 mt-6">
            <button
              type="button"
              onClick={() => window.close()}
              className="btn-secondary flex-1"
              aria-label="Cancelar"
              disabled={isLoading}
            >
              Cancelar
            </button>
            <button
              type="submit"
              className="btn-primary flex-1 disabled:opacity-50 disabled:cursor-not-allowed"
              aria-label="Entrar"
              disabled={isLoading}
            >
              {isLoading ? 'Entrando...' : 'Entrar'}
            </button>
          </div>

          {/* Recuperar senha */}
          <p className="mt-4 text-sm text-neutral-gray text-center">
            Esqueceu a senha?{' '}
            <button
              type="button"
              onClick={onForgotPassword}
              className="text-primary hover:text-primary-hover font-medium transition-all duration-150 underline"
              aria-label="Recuperar senha"
              disabled={isLoading}
            >
              Clique aqui
            </button>
          </p>
        </form>
      </div>
    </div>
    </>
  );
}
