// GENERATED BY CLAUDE - 2025-11-03
import { useState } from 'react';
import Dialog from '../../components/Dialog';

interface LoginProps {
  onLoginSuccess: (email: string, password: string) => void;
  onForgotPassword: () => void;
}

export default function LoginPage({ onLoginSuccess, onForgotPassword }: LoginProps) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [dialog, setDialog] = useState<{
    isOpen: boolean;
    title: string;
    message: string;
    type: 'error' | 'success' | 'info' | 'warning';
  }>({ isOpen: false, title: '', message: '', type: 'info' });

  // Validação: Email e senha
  const validarEmail = (val: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val);
  const validarPassword = (val: string) => val.trim().length >= 6;

  const showDialog = (title: string, message: string, type: 'error' | 'success' | 'info' | 'warning' = 'info') => {
    setDialog({ isOpen: true, title, message, type });
  };

  const closeDialog = () => {
    setDialog({ ...dialog, isOpen: false });
  };

  const handleLogin = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    
    if (!validarEmail(email)) {
      showDialog('Email Inválido', 'Por favor, insira um endereço de email válido.', 'warning');
      return;
    }
    
    if (!validarPassword(password)) {
      showDialog('Senha Inválida', 'A senha deve ter no mínimo 6 caracteres.', 'warning');
      return;
    }
    
    setIsLoading(true);
    try {
      await onLoginSuccess(email, password);
    } catch (error) {
      // Erro já tratado no App.tsx
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <>
      <Dialog
        isOpen={dialog.isOpen}
        onClose={closeDialog}
        title={dialog.title}
        message={dialog.message}
        type={dialog.type}
      />
      <div className="fixed inset-0 bg-accent flex items-center justify-center p-4">
      <div className="bg-white rounded-xl shadow-lg w-full max-w-md p-8 border border-border-light">
        {/* Título */}
        <div className="text-center mb-8">
          <div className={`w-20 h-20 rounded-full bg-primary flex items-center justify-center mx-auto mb-4 ${isLoading ? 'animate-spin' : ''}`}>
            <img
              src="https://cdn-icons-png.flaticon.com/512/29/29302.png"
              alt="Livro"
              className="w-12 h-12 brightness-0 invert"
            />
          </div>
          <h2 className="text-2xl font-semibold text-text-primary">
            Sistema de Gestão Escolar
          </h2>
          <p className="text-sm text-neutral-gray mt-2">Faça login para continuar</p>
        </div>

        {/* Campos */}
        <form onSubmit={handleLogin} className="space-y-4">
          <div>
            <label className="block mb-2 text-sm font-medium text-text-primary">Email</label>
            <input
              type="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              placeholder="seu.email@escola.com"
              className="input-field"
              aria-label="Email"
              disabled={isLoading}
            />
          </div>
          <div>
            <label className="block mb-2 text-sm font-medium text-text-primary">Senha</label>
            <div className="relative">
              <input
                type={showPassword ? "text" : "password"}
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                placeholder="Digite sua senha"
                className="input-field pr-10"
                aria-label="Senha"
                disabled={isLoading}
                onKeyPress={(e) => e.key === 'Enter' && handleLogin()}
              />
              <button
                type="button"
                onClick={() => setShowPassword(!showPassword)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-neutral-gray hover:text-text-primary transition-colors"
                aria-label={showPassword ? "Esconder senha" : "Mostrar senha"}
                disabled={isLoading}
              >
                {showPassword ? (
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path fillRule="evenodd" d="M3.707 2.293a1 1 0 00-1.414 1.414l14 14a1 1 0 001.414-1.414l-1.473-1.473A10.014 10.014 0 0019.542 10C18.268 5.943 14.478 3 10 3a9.958 9.958 0 00-4.512 1.074l-1.78-1.781zm4.261 4.26l1.514 1.515a2.003 2.003 0 012.45 2.45l1.514 1.514a4 4 0 00-5.478-5.478z" clipRule="evenodd" />
                    <path d="M12.454 16.697L9.75 13.992a4 4 0 01-3.742-3.741L2.335 6.578A9.98 9.98 0 00.458 10c1.274 4.057 5.065 7 9.542 7 .847 0 1.669-.105 2.454-.303z" />
                  </svg>
                ) : (
                  <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                    <path d="M10 12a2 2 0 100-4 2 2 0 000 4z" />
                    <path fillRule="evenodd" d="M.458 10C1.732 5.943 5.522 3 10 3s8.268 2.943 9.542 7c-1.274 4.057-5.064 7-9.542 7S1.732 14.057.458 10zM14 10a4 4 0 11-8 0 4 4 0 018 0z" clipRule="evenodd" />
                  </svg>
                )}
              </button>
            </div>
          </div>

          {/* Botão */}
          <div className="mt-6">
            <button
              type="submit"
              className="btn-primary w-full disabled:opacity-50 disabled:cursor-not-allowed inline-flex items-center justify-center gap-2"
              aria-label="Entrar"
              disabled={isLoading}
            >
              {isLoading && (
                <span className="inline-block w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" aria-hidden="true"></span>
              )}
              {isLoading ? 'Entrando...' : 'Entrar'}
            </button>
          </div>

          {/* Recuperar senha */}
          <p className="mt-4 text-sm text-neutral-gray text-center">
            Esqueceu a senha?{' '}
            <button
              type="button"
              onClick={onForgotPassword}
              className="text-primary hover:text-primary-hover font-medium transition-all duration-150 underline"
              aria-label="Recuperar senha"
              disabled={isLoading}
            >
              Clique aqui
            </button>
          </p>
        </form>
      </div>
    </div>
    </>
  );
}
