// GENERATED BY CLAUDE - 2025-11-03
import api from './api';
import { Relatorio, CreateRelatorioDto } from '../types/models';

export const relatoriosService = {
  getAll: async (): Promise<Relatorio[]> => {
    // TODO: Integrar com endpoint real
    const response = await api.get('/relatorios');
    return response.data;
  },

  getById: async (id: number): Promise<Relatorio> => {
    const response = await api.get(`/relatorios/${id}`);
    return response.data;
  },

  generate: async (data: CreateRelatorioDto): Promise<Relatorio> => {
    const response = await api.post('/relatorios/gerar', data);
    return response.data;
  },

  download: async (id: number): Promise<Blob> => {
    const response = await api.get(`/relatorios/${id}/download`, {
      responseType: 'blob'
    });
    return response.data;
  },

  delete: async (id: number): Promise<void> => {
    await api.delete(`/relatorios/${id}`);
  }
};

export default relatoriosService;
