// GENERATED BY CLAUDE - 2025-11-03
export { default as TurmasPage } from './TurmasPage';
export { default as ClassesFormPage } from './ClassesFormPage';
export { default as DisciplinasFormPage } from './DisciplinasFormPage';
