// GENERATED BY CLAUDE - 2025-11-03
import { useState } from 'react';
import { User, Mail, Lock, Save } from 'lucide-react';

export default function PerfilPage() {
  const [nome, setNome] = useState('');
  const [email, setEmail] = useState('');
  const [senhaAtual, setSenhaAtual] = useState('');
  const [novaSenha, setNovaSenha] = useState('');

  const handleSave = async () => {
    try {
      // TODO: Integrar com API real
      alert('✅ Perfil atualizado com sucesso!');
    } catch (error) {
      alert('❌ Erro ao atualizar perfil');
    }
  };

  return (
    <div className="space-y-6">
      <div className="card">
        <h2 className="text-2xl font-bold text-text-primary">Meu Perfil</h2>
        <p className="text-sm text-neutral-gray mt-1">Gerencie suas informações pessoais</p>
      </div>

      <div className="card">
        <h3 className="text-lg font-semibold text-text-primary mb-4">Informações Pessoais</h3>
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-text-primary mb-2">
              <User size={16} className="inline mr-2" />
              Nome
            </label>
            <input type="text" value={nome} onChange={(e) => setNome(e.target.value)} className="input-field" placeholder="Seu nome" />
          </div>
          <div>
            <label className="block text-sm font-medium text-text-primary mb-2">
              <Mail size={16} className="inline mr-2" />
              Email
            </label>
            <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} className="input-field" placeholder="seu@email.com" />
          </div>
        </div>
      </div>

      <div className="card">
        <h3 className="text-lg font-semibold text-text-primary mb-4">Alterar Senha</h3>
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-text-primary mb-2">
              <Lock size={16} className="inline mr-2" />
              Senha Atual
            </label>
            <input type="password" value={senhaAtual} onChange={(e) => setSenhaAtual(e.target.value)} className="input-field" />
          </div>
          <div>
            <label className="block text-sm font-medium text-text-primary mb-2">
              <Lock size={16} className="inline mr-2" />
              Nova Senha
            </label>
            <input type="password" value={novaSenha} onChange={(e) => setNovaSenha(e.target.value)} className="input-field" />
          </div>
        </div>
      </div>

      <div className="flex justify-end">
        <button onClick={handleSave} className="btn-primary flex items-center gap-2">
          <Save size={16} /> Salvar Alterações
        </button>
      </div>
    </div>
  );
}
