// GENERATED BY CLAUDE - 2025-11-03
import api from './api';
import { Horario, CreateHorarioDto } from '../types/models';

export const horariosService = {
  getAll: async (): Promise<Horario[]> => {
    // TODO: Integrar com endpoint real
    const response = await api.get('/horarios');
    return response.data;
  },

  getById: async (id: number): Promise<Horario> => {
    const response = await api.get(`/horarios/${id}`);
    return response.data;
  },

  create: async (data: CreateHorarioDto): Promise<Horario> => {
    const response = await api.post('/horarios', data);
    return response.data;
  },

  update: async (id: number, data: Partial<CreateHorarioDto>): Promise<Horario> => {
    const response = await api.put(`/horarios/${id}`, data);
    return response.data;
  },

  delete: async (id: number): Promise<void> => {
    await api.delete(`/horarios/${id}`);
  },

  getByTurma: async (turma: string): Promise<Horario[]> => {
    const response = await api.get(`/horarios/turma/${turma}`);
    return response.data;
  }
};

export default horariosService;
