// GENERATED BY CLAUDE - 2025-11-03
import { useState, useEffect } from 'react';
import { FileText, Plus } from 'lucide-react';

export default function ExamesPage() {
  const [exames, setExames] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchExames();
  }, []);

  const fetchExames = async () => {
    try {
      // TODO: Integrar com API real
      const res = await fetch('http://localhost:3000/api/exames');
      if (res.ok) {
        const data = await res.json();
        setExames(data);
      }
    } catch (error) {
      console.error('Erro ao carregar exames:', error);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="card">
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-2xl font-bold text-text-primary">Exames</h2>
            <p className="text-sm text-neutral-gray mt-1">Gestão de pacotes de exames</p>
          </div>
          <button className="btn-primary flex items-center gap-2">
            <Plus size={16} /> Novo Exame
          </button>
        </div>
      </div>

      <div className="card">
        {loading ? (
          <p className="text-neutral-gray">Carregando...</p>
        ) : exames.length === 0 ? (
          <div className="text-center py-12">
            <FileText className="mx-auto text-neutral-gray mb-4" size={48} />
            <p className="text-neutral-gray">Nenhum exame cadastrado</p>
          </div>
        ) : (
          <div className="space-y-4">
            {exames.map((exame, i) => (
              <div key={i} className="p-4 border border-border-light rounded-lg hover:shadow-md transition-shadow">
                <h3 className="font-semibold text-text-primary">{exame.nome}</h3>
                <p className="text-sm text-neutral-gray mt-1">{exame.descricao}</p>
                <div className="flex gap-4 mt-2 text-sm">
                  <span className="text-neutral-gray">Classe: {exame.classe}</span>
                  <span className="text-neutral-gray">Ano: {exame.ano_letivo}</span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
