// GENERATED BY CLAUDE - 2025-11-03
import { useState } from 'react';
import { FileText, Download } from 'lucide-react';

export default function RelatoriosPage() {
  const [tipoRelatorio, setTipoRelatorio] = useState('');
  const [periodoInicio, setPeriodoInicio] = useState('');
  const [periodoFim, setPeriodoFim] = useState('');

  const handleGenerate = async () => {
    if (!tipoRelatorio || !periodoInicio || !periodoFim) {
      alert('Preencha todos os campos');
      return;
    }

    try {
      // TODO: Integrar com API real
      const res = await fetch('http://localhost:3000/api/relatorios/gerar', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ tipo: tipoRelatorio, periodo_inicio: periodoInicio, periodo_fim: periodoFim })
      });

      if (res.ok) {
        alert('✅ Relatório gerado com sucesso!');
      }
    } catch (error) {
      alert('❌ Erro ao gerar relatório');
    }
  };

  return (
    <div className="space-y-6">
      <div className="card">
        <h2 className="text-2xl font-bold text-text-primary">Relatórios</h2>
        <p className="text-sm text-neutral-gray mt-1">Gere relatórios personalizados</p>
      </div>

      <div className="card">
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-text-primary mb-2">Tipo de Relatório</label>
            <select value={tipoRelatorio} onChange={(e) => setTipoRelatorio(e.target.value)} className="input-field">
              <option value="">Selecione...</option>
              <option value="Financeiro">Financeiro</option>
              <option value="Acadêmico">Acadêmico</option>
              <option value="Presença">Presença</option>
              <option value="Geral">Geral</option>
            </select>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium text-text-primary mb-2">Período Início</label>
              <input type="date" value={periodoInicio} onChange={(e) => setPeriodoInicio(e.target.value)} className="input-field" />
            </div>
            <div>
              <label className="block text-sm font-medium text-text-primary mb-2">Período Fim</label>
              <input type="date" value={periodoFim} onChange={(e) => setPeriodoFim(e.target.value)} className="input-field" />
            </div>
          </div>

          <button onClick={handleGenerate} className="btn-primary flex items-center gap-2">
            <Download size={16} /> Gerar Relatório
          </button>
        </div>
      </div>

      <div className="card">
        <h3 className="text-lg font-semibold text-text-primary mb-4">Relatórios Recentes</h3>
        <div className="text-center py-8">
          <FileText className="mx-auto text-neutral-gray mb-4" size={48} />
          <p className="text-neutral-gray">Nenhum relatório gerado ainda</p>
        </div>
      </div>
    </div>
  );
}
